default['bwpluginrestjson-install']['install']['group'] = 'sgsup'
default['bwpluginrestjson-install']['install']['user'] = 'esbuser'
default['bwpluginrestjson-install']['config']['group'] = 'sgsup'
default['bwpluginrestjson-install']['config']['user'] = 'esbuser'

default['bwpluginrestjson-install']['install']['tibco_home_name'] = 'TIBCO_HOME'
default['bwpluginrestjson-install']['install']['tibco_home_dir'] = '/apps/tibco'
default['bwpluginrestjson-install']['install']['logs_home_dir'] = '/logs/tibco'
default['bwpluginrestjson-install']['install']['tibco_install_dir'] = '/apps/tibco'
default['bwpluginrestjson-install']['install']['tibco_instance_dir'] = '/apps/tibco'
default['bwpluginrestjson-install']['install']['logs_instance_dir'] = '/logs/tibco'

default['bwpluginrestjson-install']['install']['bwpluginrestjson_bin_source'] = 'https://s3-us-west-2.amazonaws.com/restjsonplugin-2.0.0-bin/linux/TIB_bwpluginrestjson_2.0.0_linux26gl23_x86.zip'
default['bwpluginrestjson-install']['install']['bwpluginrestjson_bin_target_path'] = '/tmp/bwpluginrestjson'
default['bwpluginrestjson-install']['install']['bwpluginrestjson_bin_zip'] = 'TIB_bwpluginrestjson_2.0.0_linux26gl23_x86.zip'
default['bwpluginrestjson-install']['install']['tibco_universalinstaller_bin'] = 'TIBCOUniversalInstaller-lnx-x86.bin'
default['bwpluginrestjson-install']['install']['response_file'] = 'bwpluginrestjsonInstallResponseFile.silent'
default['bwpluginrestjson-install']['install']['restjsonplugin_jar'] = '/apps/tibco/eai/4.0/bw/plugins/lib/palettes/restjsonplugin.jar'

default['java']['install_flavor'] = 'oracle'
default['java']['jdk_version'] = '8'
default['java']['java_home'] = '/opt/jre'
default['java']['set_etc_environment'] = 'true'
default['java']['oracle']['accept_oracle_download_terms'] = 'true'
