name 'tibcohome-create'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures tibcohome-create'
long_description 'Installs/Configures tibcohome-create'
version '0.1.0'
