name 'bw-install'
maintainer 'JitheshKumar (JK)'
maintainer_email 'jiteshkumar.thekkeveettil@citi.com'
license 'all_rights'
description 'Installs the TIBCO BW'
long_description 'Installs TIBCO BW using the TIBCO Universal Installer in silent mode'
version '0.1.0'

depends 'java', '~> 1.36.0'
depends 'rv-install'
depends 'tra-install'
