default['ems-goldsettings']['config']['group'] = 'sgsup'
default['ems-goldsettings']['config']['user'] = 'esbuser'
default['ems-goldsettings']['config']['ems_install_dir'] = '/apps/tibco'
default['ems-goldsettings']['config']['ems_major_version'] = '8.2'
default['ems-goldsettings']['config']['ems_log_home'] = '/logs/tibco/ems'
default['ems-goldsettings']['config']['ems_config_home'] = '/apps/tibco/config/ems'
default['ems-goldsettings']['config']['ems_instance_name'] = 'TEST_EMS'

default['ems-goldsettings']['tibemsd_config']['handshake_timeout'] = '30'
default['ems-goldsettings']['tibemsd_config']['max_msg_memory'] = '2GB'
default['ems-goldsettings']['tibemsd_config']['authorization'] = 'enabled'
default['ems-goldsettings']['tibemsd_config']['routing'] = 'enabled'
default['ems-goldsettings']['tibemsd_config']['flow_conrol'] = 'enabled'
default['ems-goldsettings']['tibemsd_config']['ft_heartbeat'] = '3'
default['ems-goldsettings']['tibemsd_config']['ft_activation'] = '30'
default['ems-goldsettings']['tibemsd_config']['ft_reconnect_timeout'] = '360'
default['ems-goldsettings']['tibemsd_config']['client_timeout_server_connection'] = '300'
default['ems-goldsettings']['tibemsd_config']['server_timeout_client_connection'] = '300'
default['ems-goldsettings']['tibemsd_config']['server_timeout_server_connection'] = '300'

default['ems-goldsettings']['factories_config']['ssl_port'] = '8243'
default['ems-goldsettings']['factories_config']['connect_attempt_count'] = '10'
default['ems-goldsettings']['factories_config']['connect_attempt_delay'] = '10000'
default['ems-goldsettings']['factories_config']['connect_attemp_timeout'] = '30000'
default['ems-goldsettings']['factories_config']['reconnect_attempt_count'] = '300'
default['ems-goldsettings']['factories_config']['reconnect_attempt_delay'] = '10000'
default['ems-goldsettings']['factories_config']['reconnect_attempt_timeout'] = '30000'
