default['tra-install']['install']['group'] = 'sgsup'
default['tra-install']['install']['user'] = 'esbuser'
default['tra-install']['config']['group'] = 'sgsup'
default['tra-install']['config']['user'] = 'esbuser'

default['tra-install']['install']['tibco_home_name'] = 'TIBCO_HOME'
default['tra-install']['install']['tibco_home_dir'] = '/apps/tibco'
default['tra-install']['install']['logs_home_dir'] = '/logs/tibco'
default['tra-install']['install']['tibco_install_dir'] = '/apps/tibco'
default['tra-install']['install']['tibco_instance_dir'] = '/apps/tibco'
default['tra-install']['install']['logs_instance_dir'] = '/logs/tibco'

default['tra-install']['install']['tra_bin_source'] = 'https://s3-us-west-2.amazonaws.com/tra-5.10.0-bin/linux/TIB_TRA_5.10.0_linux_x86.zip'
default['tra-install']['install']['tra_bin_target_path'] = '/tmp/tra'
default['tra-install']['install']['tra_bin_zip'] = 'TIB_TRA_5.10.0_linux_x86.zip'
default['tra-install']['install']['tibco_universalinstaller_bin'] = 'TIBCOUniversalInstaller-lnx-x86.bin'
default['tra-install']['install']['response_file'] = 'traInstallResponseFile.silent'

default['tra-install']['install']['tra_home_dir'] = '/apps/tibco/tra/5.10'
default['tra-install']['install']['logs_home_tra'] = '/logs/tibco/tra/5.10'

default['java']['install_flavor'] = 'oracle'
default['java']['jdk_version'] = '8'
default['java']['java_home'] = '/opt/jre'
default['java']['set_etc_environment'] = 'true'
default['java']['oracle']['accept_oracle_download_terms'] = 'true'
